name: train_de_mots
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  diacritic: ^0.1.4
  twitch_manager:
    path: ./plugins/twitch_manager
  collection: ^1.17.2
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/music/TheSwindler.mp3
    - assets/music/TrainWhistle.mp3